# Generated by Django 4.1.13 on 2025-03-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task1',
            old_name='status',
            new_name='availability',
        ),
    ]
